title: "Jiaxing's Terminal Blog"
description: "Notes on software engineering, thinking, and building."
baseurl: "/jiaxing-s-blog"
url: "https://p81sunshine.github.io"
repository: "p81sunshine/jiaxing-s-blog"
lang: "en"
theme: jekyll-theme-hacker
permalink: /posts/:year/:month/:day/:title/
timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
      author: Jiaxing
